name: Release Tag
description: "sd"

inputs:
  name:
    description: some text
    required:  false

outputs:
  tag:
    description: "tag"
    value: ${{ steps.set-tag.outputs.tag }}

runs:
  using: 'composite'
  steps:
    - name: set release Tag
      id: set-tag
      shell: bash
      run: |
        echo $GITHUB_REF
        case "$GITHUB_REF" in
          refs/tags/*)
          TAG=${GITHUB_REF#refs/tags/}
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          ;;
        esac

    - name: check script
      shell: bash
      run: |
        echo ${{ inputs.name }}
        if [[ -n ${{ inputs.name }} ]]; then
          echo "inside if"
        fi
