name: Release Tag
description: "sd"

inputs:
  name:
    description: some text
    required:  false

outputs:
  tag:
    description: "tag"
    value: ${{ steps.set-tag.outputs.tag }}

runs:
  using: 'composite'
  steps:
    - name: set release Tag
      id: set-tag
      shell: bash
      run: |
        echo $GITHUB_REF
          TAG=${GITHUB_REF#refs/tags/}
          echo $TAG

    - name: check script
      shell: bash
      run: |
        echo ${{ inputs.name }}
        if [[ -n "${{ inputs.name }}" ]]; then
          echo "inside if"
        fi

    - name: check condition
      shell: bash
      run: |
        echo ${{ github.event_name }}  ${{ github.ref }}
        if [[ ( "${{ github.event_name }}" == 'release' || "${{ github.ref }}" == 'refs/heads/main' ) ]]; then
          echo "inside if"
        else
          echo "inside else"
        fi
