name: validate release
on:
  release:
  push:
  
jobs:
  validate-tags:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - uses: ./actions

    - run: echo ${{ steps.set-tag.outputs.tag }}
